### ISSUE TITLE
Fabric Modded CrossStich 0.1.4

### ISSUE THREAD

**Issue by Phelms215** [VelocityPowered/CrossStitch#5] opened 2022-03-26 17:55 UTC
Attempting to run CrossStich 0.1.4 with a fabric modded (1.18.1) server and it doesn't appear that crossstich does anything. Whenever connecting through Velocity I get "prompts that I need to install a mod version to match the server" 

I can connect directly to the server around Velocity.
I have Velocity set in modern and passing all through at the moment.

**Comment by astei** [comment] 2022-03-26 20:01
Without a mod list or exact errors I cannot possibly identify the issue.

**Comment by Phelms215** [comment] 2022-03-26 20:42
Gotcha - I am using the Medieval Minecraft pack at the moment on 1.18.1. I will get the complete modlist added shortly
https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric

The client sees [this error](https://i.imgur.com/nqeCW13.png)
The fabric server sees:
`
[20:40:31] [Netty Epoll Server IO #6/INFO]: Disconnecting com.mojang.authlib.GameProfile@7f1c7b11[id=d387c55a-dcbb-4811-850c-ab2fef70cefa,name=---] Disconnected: server requires client to have Data Attributes version 1.1.5.
[20:40:31] [Server thread/INFO]: com.mojang.authlib.GameProfile---,properties={textures=[com.mojang.authlib.properties.Property@68cfac62]},legacy=false] --- lost connection: Disconnected: server requires client to have Data Attributes version 1.1.5.
`

and the proxy similar
`
[20:40:31] [Netty epoll Worker #17/INFO]: [server connection] PHELMS -> modded has connected
[20:40:31] [Netty epoll Worker #17/INFO]: [server connection] PHELMS -> modded has disconnected
[20:40:31] [Netty epoll Worker #17/ERROR]: [connected player] PHELMS: disconnected while connecting to modded: Disconnected: server requires client to have Data Attributes version 1.1.5.
[20:40:31] [Netty epoll Worker #17/INFO]: [connected player] PHELMS has disconnected: Unable to connect to modded: Disconnected: server requires client to have Data Attributes version 1.1.5.
`

If I remove the mods it complains about from client & server it seems to just go to the next mod in the list - and I can always connect when going directly to the server not through Velocity

**Comment by astei** [comment] 2022-04-16 15:47
This is caused by mods requiring the presence of the mod to be detected by the server, doing this via login plugin messages. We're not interested in trying to hack around this, given that Velocity now has a login plugin message API that now fills the void for this. The possible number of permutations here is so large that we simply cannot commit to supporting every mod under the sun, and therefore we provide a generic login plugin message API.

Closing because there's almost nothing we can do in CrossStitch.

**Closed by astei** 2022-04-16 15:47 UTC
