### ISSUE TITLE
Fabric 1.17.1 support

### ISSUE THREAD

**Issue by JacksonBarker** [VelocityPowered/CrossStitch#3] opened 2021-08-19 00:43 UTC
crossstitch-0.1.4.jar does not work on a Fabric server running a Minecraft 1.17.1 modpack and during my testing, I did not even see any mention of CrossSwitch in the server's log during the server's startup

The error I receive when trying to connect to the server through Velocity is "This server requires you to install the Origins mod (v1.0.3) to play." While the server works normally when connecting directly via LAN.

Fabric server version: 1.17.1 (0.11.6)
Modpack: [Medieval Minecraft [FABRIC] - 1.17.1 (v10.5)](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric/files/3429829) (Without The Aether mod)
Velocity proxy local IP: 192.168.0.148
Pastebin: [https://pastebin.com/dA36D1mY](https://pastebin.com/dA36D1mY)

**Comment by astei** [comment] 2021-08-19 01:21
You need to disable the version check in the Origins mod configuration. This is not a bug in Velocity or CrossStitch so I’m closing this issue.

**Closed by astei** 2021-08-19 01:21 UTC

**Comment by JacksonBarker** [comment] 2021-08-19 01:29
Can't believe my assessment of the issue was so misguided, though I am still a little confused as to why this only happens when connecting through a proxy (Question for the Origin devs I guess).

Sorry for wasting your time, thanks for your help @astei
